openapi: 3.0.0
info:
  title: Music Library API
  description: A compact API for managing artists and their songs.
  version: 1.0.0
servers:
  - url: '/api/music-library'
    
paths:
  /health:
    head: 
      summary: API health check
      tags:
        - artist
      operationId: healthCheck
      responses: 
        '200':
          description: Returns when API server is running
  /artists:
    get:
      summary: Get all artists
      tags:
        - artist
      operationId: getArtists
      responses:
        '200':
          description: A list of artists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'schemas.yaml#/components/schemas/Artist'
    post:
      summary: Create a new artist
      tags:
        - artist
      operationId: createArtist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas.yaml#/components/schemas/ArtistInput'
      responses:
        '201':
          description: Artist created
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Artist'

  /artists/{artistId}:
    delete:
      summary: Delete an artist by ID
      tags:
        - artist
      operationId: deleteArtist
      parameters:
        - name: artistId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Artist deleted

  /artists/{artistId}/songs:
    post:
      summary: Add a song to an artist
      tags:
        - artist
      operationId: createSongForArtist
      parameters:
        - name: artistId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas.yaml#/components/schemas/SongInput'
      responses:
        '201':
          description: Song created
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Song'

    get:
      summary: Get all songs by an artist
      tags:
        - artist
      operationId: getSongsOfArtist
      parameters:
        - name: artistId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of songs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'schemas.yaml#/components/schemas/Song'
  
  /releaseName:
    get: 
      summary: Get the name of the current API release
      tags:
        - artist
      operationId: getReleaseName
      responses: 
        200:
          description: Release name
          content:
            text/plain:
              schema: 
                type: string
